# Generated by Django 3.2.18 on 2023-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('anoLancamento', models.IntegerField()),
            ],
            options={
                'db_table': 'livros',
            },
        ),
    ]
